server:
  port: 8111

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/white_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
#  redis:
#    host: 127.0.0.1 # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: # Redis服务器连接密码（默认为空）
#    jedis:
#      pool:
#        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10 # 连接池中的最大空闲连接
#        min-idle: 5 # 连接池中的最小空闲连接
#    timeout: 3000 # 连接超时时间（毫秒）

#jwt配置
dhb:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: authorization

mybatis-plus:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.number47.white.blog # mybatis 别名包扫描路径
  global-config:
    db-config:
      logic-delete-value: 1 #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

img:
  url: http://localhost:8080/file/
  path: D://file/

password:
  defaultPassword: 1234567 #默认密码长度6-15
  isClear: false #是否明文 没实现
  min: 3 #暂时没实现
  max: 15 #暂时没实现
